### PR TITLE
fix: scancodes for native ironrdp-client incorrect on MacOS

### PR DESCRIPTION
**Pull request by zmrush**
Fixes https://github.com/Devolutions/IronRDP/issues/180

### CODE REVIEW

**Comment by zmrush** [comment]
@elmarco @sandeepbansal @CBenoit can u review this pr for bug fix?

**Review by CBenoit — CHANGES_REQUESTED** [review]
Thank you for attempting to fix this!
Unfortunately, using virtual keycodes is not the right approach here.
In this case, the QWERTY layout is assumed, but everything breaks as soon as you use something else.
There are also other shortcomings related to special characters.

Actually, I was working on a fix in this branch: https://github.com/Devolutions/IronRDP/tree/scancode-mapping

In essence, what we need is a big `match` for mapping Apple scancodes to Windows scancodes.

**Comment by thenextman** [comment]
Also to note that even for Windows, you wouldn't use a static map of VKCode to scancode. `MapVirtualKey` and `MapVirtualKeyEx` achieve this according to the current keyboard layout.

**Comment by zmrush** [comment]
@CBenoit  i am sorry for reply u so late. I am very interesting for this. And I am working on solving this according to your advice, based on freerdp and I almost finished it. In addition,  i am also doing work for file uploading/downloading,  and i test a lot, and i think i almost finish it. I expect i will give the pr, next week maybe. thank u so much.

**Pull request closed without merging**
