### PR TITLE
chore(ironrdp_client): update sspi-rs version

### PR DESCRIPTION
**Pull request by RRRadicalEdward**

### CODE REVIEW

**Comment by CBenoit** [comment]
If it’s okay with you, I’ll update in our hackaton (wasm-client) branch to avoid conflicts.

**Comment by RRRadicalEdward** [comment]
I suspect the compilation of `sspi-rs` is broken on `macOS` and `Linux`. Let me check

**Comment by CBenoit** [comment]
Thank you!

**Comment by RRRadicalEdward** [comment]
@awakecoding Could you merge?
Thanks!

**Review by awakecoding — APPROVED** [review]

**Pull request merged**
