### PR TITLE
Update dependency versions and other minor cleanups

### PR DESCRIPTION
**Pull request by dheater**
Update version dependencies except for `bitvec` which is 1.0 now and has many breaking changes (will put in a separate PR).

### CODE REVIEW

**Review by CBenoit — APPROVED** [review]
LGTM, thank you!

**Comment by CBenoit** [comment]
> except for `bitvec` which is 1.0 now and has many breaking changes (will put in a separate PR).

Hi! Did you get a chance to look into it since then? Just asking because I was considering updating it too but I don’t want to duplicate the work. Thank you 🙂

**Comment by dheater** [comment]
> > except for `bitvec` which is 1.0 now and has many breaking changes (will put in a separate PR).
> 
> Hi! Did you get a chance to look into this? Just asking because I was considering updating it soon as well, but I don’t want to duplicate the work. Thank you 🙂

I haven't looked into it yet so go for it 🙂

**Comment by CBenoit** [comment]
Perfect thank you! 😄

**Pull request merged**
