### PR TITLE
Improvements for dynamic channel handling

### PR DESCRIPTION
**Pull request by msabansal**
In summary the PR has following changes:

1. Adding some improvements on how IronRDP handles dynamic channels.
2. Added a handler for display pipeline to handle monitor layout changes
3. Added proper handling to allow connecting to gfx pipeline.
4. All new changes are disabled by default and there are command line options to enable them.
5. Fix some clippy errors in existing code.
6. Minor workaround for https://github.com/Devolutions/IronRDP/issues/45
7. Updated some of the crates to the latest version

Most of the changes here were done a few months back in an attempt to build a gui based on IronRDP. 

Some fuzz tests are missing because i was not sure how to add them.

### CODE REVIEW

**Comment by msabansal** [comment]
Will resolve the formatting issues in some time.

**Comment by awakecoding** [comment]
Wow, thanks a lot! Did you manage to build a simple GUI for IronRDP? It's something we'd really need to make the project a lot more usable beyond a library. We've looked into a few cross-platform frameworks like Tauri, but there's also native-windows-gui that would be great to make an mstsc-like clone on Windows. We have a lot of space of improvement and welcome any contributions!

**Comment by msabansal** [comment]
I added a very simple one that could handle only h264 stream. It was based of https://github.com/grovesNL/glow. When I get time I will clean it up and submit a pr for it for sure.

That is the intent of submitting this PR.

Thanks for you and your team for making and open sourcing this library

**Review by awakecoding — APPROVED** [review]
LGTM

**Comment by awakecoding** [comment]
@msabansal out of curiosity, which H.264 decoder library did you use in your project? If you're interested, there are a few undocumented registry keys in the RDP server that you can use to tweak the H.264 encoder, and even have it dump the entire bitstream to a replayable file: https://blog.devolutions.net/2021/12/finding-secret-rdp-registry-keys-using-ida-free/

**Comment by msabansal** [comment]
Openh264-rust. I will hide the code behind an experimental flag and submit a pr for it. All the code was written when I was just a couple weeks into experimenting with rust so it's in pretty bad shape and needs a fair bit of cleanup. If I remember correctly I was able to get it to a shape where the session was responsive and would run on windows and linux. Most of the changes needed in ironrdp itself are now in the library with this pr.

**Comment by msabansal** [comment]
The keys are good knowledge  i modified freerdp client to dump the stream into a file which was fairly quick

**Pull request merged**
